version: "3.9"

services:
  danacup_db_postgresql:
    image: postgres:latest
    container_name: danacup_db_postgresql
    volumes:
      - danacup_db_postgresql:/var/lib/postgresql/data
    restart: always
    env_file:
      - .docker.env
    ports:
      - "5432:5432"
    networks:
      - danacup_app

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    env_file:
      - .docker.env
    networks:
      - danacup_app
    volumes:
      - ./pg_servers/servers.json:/pgadmin4/servers.json

  # danacup_backend:
  #   build:
  #     context: ../server
  #     dockerfile: Dockerfile
  #   container_name: danacup_backend
  #   restart: always
  #   volumes:
  #     - static_volume:/app/static
  #     - media_volume:/app/media
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ../server/docker.env
  #   depends_on:
  #     - danacup_db_postgresql
  #   networks:
  #     - danacup_app

volumes:
  danacup_db_postgresql:
    external: true
  static_volume:
  media_volume:

networks:
  danacup_app:
    external: true
