version: "3"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      # - N8N_RUNNERS_ENABLED=true
      # For external database, we can enable the following settings:
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n
      # To communicate with ollama, the service name is used as the host.
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - n8n-network
    # For Mac with M1/M2/M3 chips we use arm64 platform
    platform: linux/arm64/v8
    # For Mac with Intel processor use the following line
    # platform: linux/amd64

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=admin
    # - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - n8n-network

# If we want to use PostgreSQL database, uncomment the following service
# postgres:
#   image: postgres:13
#   container_name: n8n-postgres
#   restart: always
#   environment:
#     - POSTGRES_USER=n8n
#     - POSTGRES_PASSWORD=n8n
#     - POSTGRES_DB=n8n
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   networks:
#     - n8n-network

volumes:
  n8n_data:
    external: true
  ollama_data:
    external: true
  mongodb_data:
    external: true
  # If we have already created the ollama volume, set external: true
  # postgres_data:
  #   external: false

networks:
  n8n-network:
    # driver: bridge
    external: true
